In [5]:
!pip install ipython-sql 

You should consider upgrading via the '/home/sivikt/Documents/sdev/sql-ex/py3env/bin/python3 -m pip install --upgrade pip' command.


In [6]:
import sqlalchemy
import matplotlib.pyplot as plt

In [14]:
%load_ext sql
%config SqlMagic.autocommit=False # for engines that do not support autommit

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [8]:
postgres_engine = sqlalchemy.create_engine('postgresql://test:test@localhost/sqlexdb')

In [9]:
%config SQL.conn_name = 'postgres_engine'

In [13]:
%sql postgresql://test:test@localhost/sqlexdb

'Connected: test@sqlexdb'

In [11]:
%%sql
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema';

UsageError: Cell magic `%%sql` not found.


## Examples

In [30]:
res = %sql SELECT id_comp, name FROM public.company

res.DataFrame().head()

 * postgresql://test:***@localhost/sqlexdb
5 rows affected.


id_comp        name
0        1  Don_avia  
1        2  Aeroflot  
2        3  Dale_avia 
3        4  air_France
4        5  British_AW

In [31]:
table_name = 'public.company'
cols = ','.join(['id_comp', 'name'])

In [33]:
%%read_sql df_result
SELECT {cols}
FROM {table_name}

Query started at 10:52:39 AM +03; Query executed in 0.00 m

id_comp        name
0        1  Don_avia  
1        2  Aeroflot  
2        3  Dale_avia 
3        4  air_France
4        5  British_AW

# Below are SQL exercises from http://sql-ex.ru/

## Tables descriptions

###### 1 Computer firm
The database scheme consists of four tables:  
Product(maker, model, type)  
PC(code, model, speed, ram, hd, cd, price)  
Laptop(code, model, speed, ram, hd, screen, price)  
Printer(code, model, color, type, price)  
The Product table contains data on the maker, model number, and type of product ('PC', 'Laptop', or 'Printer'). It is assumed that model numbers in the Product table are unique for all makers and product types. Each personal computer in the PC table is unambiguously identified by a unique code, and is additionally characterized by its model (foreign key referring to the Product table), processor speed (in MHz) – speed field, RAM capacity (in Mb) - ram, hard disk drive capacity (in Gb) – hd, CD-ROM speed (e.g, '4x') - cd, and its price. The Laptop table is similar to the PC table, except that instead of the CD-ROM speed, it contains the screen size (in inches) – screen. For each printer model in the Printer table, its output type (‘y’ for color and ‘n’ for monochrome) – color field, printing technology ('Laser', 'Jet', or 'Matrix') – type, and price are specified.

###### 2 Incomes, Outcome

The firm owns several buy-back centers for collection of recyclable materials. Each of them receives funds to be paid to the recyclables suppliers. Data on funds received is recorded in the table  
Income_o(point, date, inc)  
The primary key is (point, date), where point holds the identifier of the buy-back center, and date corresponds to the calendar date the funds were received. The date column doesn’t include the time part, thus, money (inc) arrives no more than once a day for each center. Information on payments to the recyclables suppliers is held in the table  
Outcome_o(point, date, out)  
In this table, the primary key (point, date) ensures each buy-back center reports about payments (out) no more than once a day, too.  
For the case income and expenditure may occur more than once a day, another database schema with tables having a primary key consisting of the single column code is used:  
Income(code, point, date, inc)  
Outcome(code, point, date, out)  
Here, the date column doesn’t include the time part, either.

###### 3 Ships

The database of naval ships that took part in World War II is under consideration. The database consists of the following relations:  
Classes(class, type, country, numGuns, bore, displacement)  
Ships(name, class, launched)  
Battles(name, date)  
Outcomes(ship, battle, result)  
Ships in classes all have the same general design. A class is normally assigned either the name of the first ship built according to the corresponding design, or a name that is different from any ship name in the database. The ship whose name is assigned to a class is called a lead ship.
The Classes relation includes the name of the class, type (can be either bb for a battle ship, or bc for a battle cruiser), country the ship was built in, the number of main guns, gun caliber (bore diameter in inches), and displacement (weight in tons). The Ships relation holds information about the ship name, the name of its corresponding class, and the year the ship was launched. The Battles relation contains names and dates of battles the ships participated in, and the Outcomes relation - the battle result for a given ship (may be sunk, damaged, or OK, the last value meaning the ship survived the battle unharmed).
Notes: 1) The Outcomes relation may contain ships not present in the Ships relation. 2) A ship sunk can’t participate in later battles. 3) For historical reasons, lead ships are referred to as head ships in many exercises.4) A ship found in the Outcomes table but not in the Ships table is still considered in the database. This is true even if it is sunk.

### #1  
Find the model number, speed and hard drive capacity for all the PCs with prices below $500.
Result set: model, speed, hd.

In [14]:
%%sql
SELECT model, speed, hd FROM PC WHERE price < 500

 * postgresql://test:***@localhost/sqlexdb
4 rows affected.


[('1232', 500, 10.0),
 ('1232', 450, 8.0),
 ('1232', 450, 10.0),
 ('1260', 500, 10.0)]

### #2
List all printer makers. Result set: maker.

In [15]:
%%sql
SELECT DISTINCT maker FROM Product WHERE type = 'Printer'

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('A',), ('D',), ('E',)]

### #3
Find the model number, RAM and screen size of the laptops with prices over $1000.

In [16]:
%%sql
SELECT model, ram, screen FROM Laptop WHERE price > 1000

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('1750', 128, 14), ('1298', 64, 15), ('1752', 128, 14)]

### #4
Find all records from the Printer table containing data about color printers.

In [18]:
%%sql
SELECT * FROM Printer WHERE color = 'y'

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[(2, '1433', 'y', 'Jet', Decimal('270.00')),
 (3, '1434', 'y', 'Jet', Decimal('290.00'))]

### #5
Find the model number, speed and hard drive capacity of PCs cheaper than $600 having a 12x or a 24x CD drive.

In [19]:
%%sql
SELECT model, speed, hd FROM PC WHERE price < 600 AND (cd = '12x' OR cd = '24x')

 * postgresql://test:***@localhost/sqlexdb
4 rows affected.


[('1232', 500, 10.0),
 ('1232', 450, 8.0),
 ('1232', 450, 10.0),
 ('1260', 500, 10.0)]

### #6
For each maker producing laptops with a hard drive capacity of 10 Gb or higher, find the speed of such laptops. Result set: maker, speed.

In [21]:
%%sql
SELECT DISTINCT pd.maker, lt.speed FROM Laptop as lt
INNER JOIN Product as pd 
    ON pd.model = lt.model AND
       lt.hd >= 10

 * postgresql://test:***@localhost/sqlexdb
4 rows affected.


[('A', 750), ('A', 450), ('A', 600), ('B', 750)]

### #7
Get the models and prices for all commercially available products (of any type) produced by maker B.

In [22]:
%%sql

SELECT pc.model, pc.price FROM PC as pc INNER JOIN Product as pd ON pd.model = pc.model AND pd.maker = 'B'
UNION
SELECT lt.model, lt.price FROM Laptop as lt INNER JOIN Product as pd ON pd.model = lt.model AND pd.maker = 'B'
UNION
SELECT pr.model, pr.price FROM Printer as pr INNER JOIN Product as pd ON pd.model = pr.model AND pd.maker = 'B'

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('1750', Decimal('1200.00')), ('1121', Decimal('850.00'))]

### #8
Find the makers producing PCs but not laptops.

In [23]:
%%sql
select Distinct maker from product where  type='PC'
EXCEPT
select Distinct  maker from product where type='Laptop'

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('E',)]

### #9
Find the makers of PCs with a processor speed of 450 MHz or more. Result set: maker.

In [24]:
%%sql
SELECT DISTINCT pd.maker FROM Product as pd INNER JOIN PC as pc ON pc.model = pd.model AND pc.speed >= 450

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('B',), ('E',), ('A',)]

### #10
Find the printer models having the highest price. Result set: model, price.

In [25]:
%%sql

SELECT model, price FROM Printer WHERE price = (SELECT MAX(price) FROM Printer)

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('1276', Decimal('400.00')), ('1288', Decimal('400.00'))]

### #11
Find out the average speed of PCs.

In [16]:
%%sql
SELECT AVG(speed) FROM PC

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[(Decimal('608.3333333333333333'),)]

### #12
Find out the average speed of the laptops priced over $1000.

In [17]:
%%sql
SELECT AVG(speed) FROM LAPTOP WHERE price > 1000

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[(Decimal('700.0000000000000000'),)]

### #13
Find out the average speed of the PCs produced by maker A.

In [19]:
%%sql
SELECT AVG(pc.speed) FROM PC as pc 
INNER JOIN Product as pr ON pr.model = pc.model AND pr.maker = 'A'

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[(Decimal('606.2500000000000000'),)]

### #14
For the ships in the Ships table that have at least 10 guns, get the class, name, and country.

In [20]:
%%sql
SELECT s.class, s.name, c.country FROM Ships as s
INNER JOIN Classes as c ON c.class = s.class AND c.numGuns >= 10

 * postgresql://test:***@localhost/sqlexdb
5 rows affected.


[('Tennessee', 'California', 'USA'),
 ('North Carolina', 'North Carolina', 'USA'),
 ('Tennessee', 'Tennessee', 'USA'),
 ('North Carolina', 'Washington', 'USA'),
 ('North Carolina', 'South Dakota', 'USA')]

### #15
Get hard drive capacities that are identical for two or more PCs.
Result set: hd.

In [21]:
%%sql
SELECT hd FROM PC GROUP BY hd HAVING COUNT(hd) > 1

 * postgresql://test:***@localhost/sqlexdb
5 rows affected.


[(8.0,), (20.0,), (5.0,), (14.0,), (10.0,)]

### #16
Get pairs of PC models with identical speeds and the same RAM capacity. Each resulting pair should be displayed only once, i.e. (i, j) but not (j, i).
Result set: model with the bigger number, model with the smaller number, speed, and RAM.

In [22]:
%%sql
SELECT DISTINCT p1.model as model, p2.model as model, p1.speed as speed, p1.ram as ram 
FROM PC as p1, 
     PC as p2
WHERE p1.code != p2.code AND 
      p1.model != p2.model AND
      p1.speed = p2.speed AND 
      p1.ram = p2.ram AND 
      p1.model > p2.model	
ORDER BY p1.model DESC, p2.model ASC

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('1260', '1232', 500, 32),
 ('1233', '1121', 750, 128),
 ('1233', '1232', 500, 64)]

### #17
Get the laptop models that have a speed smaller than the speed of any PC.
Result set: type, model, speed.

In [23]:
%%sql
SELECT DISTINCT pr.type, lt.model, lt.speed 
FROM Laptop AS lt
INNER JOIN Product AS pr ON lt.model = pr.model
WHERE lt.speed < (SELECT MIN(speed) FROM PC)

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('Laptop', '1298', 350)]

### #18
Find the makers of the cheapest color printers.
Result set: maker, price.

In [24]:
%%sql
SELECT DISTINCT pr.maker, p.price 
FROM Product AS pr
INNER JOIN Printer AS p ON p.color='y' AND p.model = pr.model
WHERE p.price = (SELECT MIN(price) FROM Printer WHERE color = 'y')

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('D', Decimal('270.00'))]

### #19
For each maker having models in the Laptop table, find out the average screen size of the laptops he produces.
Result set: maker, average screen size.

In [34]:
%%sql
SELECT pr.maker, AVG(lt.screen) as Avg_screen FROM Product as pr 
INNER JOIN Laptop as lt ON lt.model = pr.model
GROUP BY pr.maker

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('B', Decimal('14.0000000000000000')),
 ('C', Decimal('12.0000000000000000')),
 ('A', Decimal('13.0000000000000000'))]

### #20
Find the makers producing at least three distinct models of PCs.
Result set: maker, number of PC models.

In [36]:
%%sql
SELECT pr.maker, COUNT(pr.model)
FROM Product as pr
WHERE pr.type = 'PC'
GROUP BY pr.maker
HAVING COUNT(pr.model) > 2

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('E', 3)]

### #21
Find out the maximum PC price for each maker having models in the PC table. Result set: maker, maximum price.

In [38]:
%%sql
SELECT p.maker, MAX(pc.price) 
FROM Product as p
INNER JOIN PC as pc ON pc.model = p.model
GROUP BY p.maker

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('B', Decimal('850.00')), ('E', Decimal('350.00')), ('A', Decimal('980.00'))]

### #22
For each value of PC speed that exceeds 600 MHz, find out the average price of PCs with identical speeds.
Result set: speed, average price.

In [37]:
%%sql
SELECT speed, AVG(price) as Avg_price
FROM PC 
WHERE speed > 600
GROUP BY speed

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[(900, Decimal('980.0000000000000000')),
 (750, Decimal('900.0000000000000000')),
 (800, Decimal('970.0000000000000000'))]

### #23
Get the makers producing both PCs having a speed of 750 MHz or higher and laptops with a speed of 750 MHz or higher.
Result set: maker

In [40]:
%%sql

SELECT p.maker
FROM Product as p
INNER JOIN PC as pc
ON pc.model = p.model AND pc.speed >= 750
INTERSECT
SELECT p1.maker
FROM Product as p1
INNER JOIN Laptop as lt 
ON lt.model = p1.model AND lt.speed >= 750

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('B',), ('A',)]

### #24
List the models of any type having the highest price of all products present in the database.

In [41]:
%%sql

WITH X(model, price) AS (
  SELECT model, price FROM PC
  UNION
  SELECT model, price FROM Laptop
  UNION
  SELECT model, price FROM Printer
)
SELECT DISTINCT model FROM X
WHERE price = (SELECT MAX(price) FROM X)

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('1750',)]

### #25
Find the printer makers also producing PCs with the lowest RAM capacity and the highest processor speed of all PCs having the lowest RAM capacity.
Result set: maker.

In [42]:
%%sql

WITH min_ram AS (
  SELECT code, model, speed FROM PC WHERE ram = (SELECT MIN(ram) FROM PC)
)

SELECT DISTINCT p.maker FROM Product as p
WHERE 
p.type = 'Printer' AND
p.maker IN (
  SELECT p.maker
  FROM Product as p
  INNER JOIN min_ram as pc ON p.model = pc.model
  WHERE pc.speed = (SELECT MAX(speed) FROM min_ram)
)

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('A',), ('E',)]

### #26
Find out the average price of PCs and laptops produced by maker A.
Result set: one overall average price for all items.

In [43]:
%%sql

SELECT AVG(U.price) FROM (
  SELECT price FROM PC as pc
  INNER JOIN Product as p ON p.model = pc.model AND p.maker = 'A'
  UNION ALL
  SELECT price FROM Laptop as lt
  INNER JOIN Product as p ON p.model = lt.model AND p.maker = 'A'
) as U

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[(Decimal('754.1666666666666667'),)]

### #27
Find out the average hard disk drive capacity of PCs produced by makers who also manufacture printers.
Result set: maker, average HDD capacity.

In [44]:
%%sql

SELECT p.maker, AVG(hd) as average_hdd FROM PC as pc
INNER JOIN Product as p 
  ON p.model = pc.model AND p.maker IN (SELECT maker FROM Product WHERE type ='Printer')
GROUP BY p.maker

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('E', 10.0), ('A', 14.75)]

### #28
Using Product table, find out the number of makers who produce only one model.

In [45]:
%%sql

SELECT COUNT(t.maker) as qty FROM (
SELECT maker FROM Product
GROUP BY maker
HAVING COUNT(maker) = 1
) as t

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[(1,)]

### #29
Under the assumption that receipts of money (inc) and payouts (out) are registered not more than once a day for each collection point [i.e. the primary key consists of (point, date)], write a query displaying cash flow data (point, date, income, expense).
Use Income_o and Outcome_o tables.

In [47]:
%%sql

SELECT i.point, i.date, i.inc, o.out
FROM Income_o as i
LEFT JOIN Outcome_o as o ON o.point = i.point AND o.date = i.date
UNION
SELECT o.point, o.date, i.inc, o.out
FROM Outcome_o as o
LEFT JOIN Income_o as i ON o.point = i.point AND o.date = i.date

 * postgresql://test:***@localhost/sqlexdb
19 rows affected.


[(3, datetime.datetime(2001, 9, 14, 0, 0), None, Decimal('2300.00')),
 (1, datetime.datetime(2001, 4, 11, 0, 0), None, Decimal('3195.04')),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('10000.00'), Decimal('1440.00')),
 (3, datetime.datetime(2001, 10, 2, 0, 0), Decimal('18000.00'), None),
 (1, datetime.datetime(2001, 3, 26, 0, 0), None, Decimal('1221.00')),
 (1, datetime.datetime(2001, 3, 28, 0, 0), None, Decimal('2075.00')),
 (2, datetime.datetime(2001, 4, 2, 0, 0), None, Decimal('2040.00')),
 (2, datetime.datetime(2001, 3, 29, 0, 0), None, Decimal('7848.00')),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('4500.00'), Decimal('2530.00')),
 (1, datetime.datetime(2001, 3, 29, 0, 0), None, Decimal('2004.00')),
 (1, datetime.datetime(2001, 4, 27, 0, 0), None, Decimal('3110.00')),
 (3, datetime.datetime(2002, 9, 16, 0, 0), None, Decimal('2150.00')),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('5000.00'), Decimal('4490.00')),
 (1, datetime.datetime(2001, 3, 23, 0, 0), Decimal('15000.00'), None),
 (1, datetime.datetime(2001, 3, 22, 0, 0), Decimal('15000.00'), None),
 (2, datetime.datetime(2001, 3, 24, 0, 0), Decimal('1500.00'), None),
 (1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('3400.00'), Decimal('3663.00')),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('11500.00'), Decimal('1500.00')),
 (1, datetime.datetime(2001, 3, 14, 0, 0), None, Decimal('15348.00'))]

### #30
Under the assumption that receipts of money (inc) and payouts (out) can be registered any number of times a day for each collection point [i.e. the code column is the primary key], display a table with one corresponding row for each operating date of each collection point.
Result set: point, date, total payout per day (out), total money intake per day (inc).
Missing values are considered to be NULL.

In [55]:
%%sql

WITH incs AS (
  SELECT i.point, i.date, SUM(i.inc) AS income
  FROM Income AS i
  GROUP BY i.point, i.date
),
outcs AS (
  SELECT o.point, o.date, SUM(o.out) AS Outcome
  FROM Outcome AS o
  GROUP BY o.point, o.date
)

SELECT i.point, i.date, o.Outcome, i.income
FROM incs AS i
LEFT JOIN outcs AS o ON o.point = i.point and o.date = i.date
UNION
SELECT o.point, o.date, o.Outcome, i.income
FROM outcs AS o
LEFT JOIN incs AS i ON o.point = i.point and o.date = i.date

ORDER BY date

-- cost       0.047015622258186
-- operations 15

 * postgresql://test:***@localhost/sqlexdb
17 rows affected.


[(1, datetime.datetime(2001, 3, 14, 0, 0), Decimal('15348.00'), None),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('2880.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 3, 22, 0, 0), None, Decimal('30000.00')),
 (1, datetime.datetime(2001, 3, 23, 0, 0), None, Decimal('15000.00')),
 (2, datetime.datetime(2001, 3, 24, 0, 0), None, Decimal('3000.00')),
 (1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('7163.00'), Decimal('7000.00')),
 (1, datetime.datetime(2001, 3, 26, 0, 0), Decimal('1221.00'), None),
 (1, datetime.datetime(2001, 3, 28, 0, 0), Decimal('2075.00'), None),
 (2, datetime.datetime(2001, 3, 29, 0, 0), Decimal('7848.00'), None),
 (1, datetime.datetime(2001, 3, 29, 0, 0), Decimal('4010.00'), None),
 (2, datetime.datetime(2001, 4, 2, 0, 0), Decimal('2040.00'), None),
 (1, datetime.datetime(2001, 4, 11, 0, 0), Decimal('3195.04'), None),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('4490.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 4, 27, 0, 0), Decimal('3110.00'), None),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('2530.00'), Decimal('4500.00')),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('2700.00'), Decimal('3100.00')),
 (3, datetime.datetime(2001, 9, 14, 0, 0), Decimal('1150.00'), None)]

In [56]:
%%sql

WITH incs AS (
  SELECT i.point, i.date, SUM(i.inc) AS income
  FROM Income AS i
  GROUP BY i.point, i.date
),
outcs AS (
  SELECT o.point, o.date, SUM(o.out) AS Outcome
  FROM Outcome AS o
  GROUP BY o.point, o.date
)

SELECT COALESCE(i.point, o.point) AS point, COALESCE(i.date, o.date) AS date, Outcome, income
FROM incs AS i
FULL JOIN outcs AS o ON i.point = o.point AND i.date = o.date
ORDER BY date

-- cost        0.046924658119678
-- operations  11

 * postgresql://test:***@localhost/sqlexdb
17 rows affected.


[(1, datetime.datetime(2001, 3, 14, 0, 0), Decimal('15348.00'), None),
 (1, datetime.datetime(2001, 3, 22, 0, 0), None, Decimal('30000.00')),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('2880.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 3, 23, 0, 0), None, Decimal('15000.00')),
 (1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('7163.00'), Decimal('7000.00')),
 (2, datetime.datetime(2001, 3, 24, 0, 0), None, Decimal('3000.00')),
 (1, datetime.datetime(2001, 3, 26, 0, 0), Decimal('1221.00'), None),
 (1, datetime.datetime(2001, 3, 28, 0, 0), Decimal('2075.00'), None),
 (2, datetime.datetime(2001, 3, 29, 0, 0), Decimal('7848.00'), None),
 (1, datetime.datetime(2001, 3, 29, 0, 0), Decimal('4010.00'), None),
 (2, datetime.datetime(2001, 4, 2, 0, 0), Decimal('2040.00'), None),
 (1, datetime.datetime(2001, 4, 11, 0, 0), Decimal('3195.04'), None),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('4490.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 4, 27, 0, 0), Decimal('3110.00'), None),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('2530.00'), Decimal('4500.00')),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('2700.00'), Decimal('3100.00')),
 (3, datetime.datetime(2001, 9, 14, 0, 0), Decimal('1150.00'), None)]

In [57]:
%%sql

WITH all_data AS (
  SELECT code, point, date, inc, NULL AS out
  FROM Income 
  UNION ALL
  SELECT code, point, date, NULL AS inc, out
  FROM outcome 
)

SELECT point, date, SUM(out) as Outcome, SUM(inc) as income
FROM all_data
GROUP BY point, date
ORDER BY date

-- cost       0.018404265865684
-- operations 8

 * postgresql://test:***@localhost/sqlexdb
17 rows affected.


[(1, datetime.datetime(2001, 3, 14, 0, 0), Decimal('15348.00'), None),
 (2, datetime.datetime(2001, 3, 22, 0, 0), Decimal('2880.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 3, 22, 0, 0), None, Decimal('30000.00')),
 (1, datetime.datetime(2001, 3, 23, 0, 0), None, Decimal('15000.00')),
 (1, datetime.datetime(2001, 3, 24, 0, 0), Decimal('7163.00'), Decimal('7000.00')),
 (2, datetime.datetime(2001, 3, 24, 0, 0), None, Decimal('3000.00')),
 (1, datetime.datetime(2001, 3, 26, 0, 0), Decimal('1221.00'), None),
 (1, datetime.datetime(2001, 3, 28, 0, 0), Decimal('2075.00'), None),
 (1, datetime.datetime(2001, 3, 29, 0, 0), Decimal('4010.00'), None),
 (2, datetime.datetime(2001, 3, 29, 0, 0), Decimal('7848.00'), None),
 (2, datetime.datetime(2001, 4, 2, 0, 0), Decimal('2040.00'), None),
 (1, datetime.datetime(2001, 4, 11, 0, 0), Decimal('3195.04'), None),
 (1, datetime.datetime(2001, 4, 13, 0, 0), Decimal('4490.00'), Decimal('10000.00')),
 (1, datetime.datetime(2001, 4, 27, 0, 0), Decimal('3110.00'), None),
 (1, datetime.datetime(2001, 5, 11, 0, 0), Decimal('2530.00'), Decimal('4500.00')),
 (3, datetime.datetime(2001, 9, 13, 0, 0), Decimal('2700.00'), Decimal('3100.00')),
 (3, datetime.datetime(2001, 9, 14, 0, 0), Decimal('1150.00'), None)]

### #31

For ship classes with a gun caliber of 16 in. or more, display the class and the country.

In [58]:
%%sql

SELECT class, country
FROM Classes
WHERE bore >= 16

 * postgresql://test:***@localhost/sqlexdb
3 rows affected.


[('Iowa', 'USA'), ('North Carolina', 'USA'), ('Yamato', 'Japan')]

### #32
One of the characteristics of a ship is one-half the cube of the calibre of its main guns (mw).
Determine the average ship mw with an accuracy of two decimal places for each country having ships in the database.

In [103]:
%%sql

SELECT c.country, CAST(AVG(0.5*c.bore*c.bore*c.bore) AS NUMERIC(6,2)) AS weight
FROM Classes AS c
INNER JOIN (
  SELECT DISTINCT o.ship, o.ship AS class FROM Outcomes AS o
  UNION
  SELECT s.name, s.class FROM Ships AS s
) alls ON alls.class = c.class
GROUP BY c.country

 * postgresql://test:***@localhost/sqlexdb
4 rows affected.


[('USA', Decimal('1897.78')),
 ('Germany', Decimal('1687.50')),
 ('Gt.Britain', Decimal('1687.50')),
 ('Japan', Decimal('1886.67'))]

### #33
Get the ships sunk in the North Atlantic battle.
Result set: ship.

In [65]:
%%sql
SELECT ship
FROM Outcomes
WHERE battle = 'North Atlantic' AND result = 'sunk'

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('Bismarck',), ('Hood',)]

### #34
In accordance with the Washington Naval Treaty concluded in the beginning of 1922, it was prohibited to build battle ships with a displacement of more than 35 thousand tons.
Get the ships violating this treaty (only consider ships for which the year of launch is known).  
List the names of the ships.

In [105]:
%%sql

SELECT s.name
FROM Classes AS c
INNER JOIN Ships AS s 
ON s.class = c.class AND 
   s.launched IS NOT NULL AND
   s.launched >= 1922 AND
   c.displacement > 35000 AND
   c.type = 'bb'

 * postgresql://test:***@localhost/sqlexdb
9 rows affected.


[('Iowa',),
 ('Missouri',),
 ('Musashi',),
 ('New Jersey',),
 ('North Carolina',),
 ('Washington',),
 ('Wisconsin',),
 ('Yamato',),
 ('South Dakota',)]

### #35
Find models in the Product table consisting either of digits only or Latin letters (A-Z, case insensitive) only.
Result set: model, type.

In [109]:
%%sql

SELECT model, type
FROM Product
WHERE UPPER(model) NOT LIKE '%[^A-Z]%' OR model NOT LIKE '%[^0-9]%'

 * postgresql://test:***@localhost/sqlexdb
16 rows affected.


[('1121', 'PC'),
 ('1232', 'PC'),
 ('1233', 'PC'),
 ('1260', 'PC'),
 ('1276', 'Printer'),
 ('1288', 'Printer'),
 ('1298', 'Laptop'),
 ('1321', 'Laptop'),
 ('1401', 'Printer'),
 ('1408', 'Printer'),
 ('1433', 'Printer'),
 ('1434', 'Printer'),
 ('1750', 'Laptop'),
 ('1752', 'Laptop'),
 ('2113', 'PC'),
 ('2112', 'PC')]

### #36
List the names of lead ships in the database (including the Outcomes table).

In [116]:
%%sql
SELECT c.class as name FROM Classes as c
INNER JOIN (
  SELECT name FROM Ships WHERE name = class
  UNION
  SELECT DISTINCT ship AS name FROM Outcomes WHERE ship NOT IN (SELECT name FROM Ships)
) s ON c.class = s.name

-- cost       0.011824180372059
-- operations 9

 * postgresql://test:***@localhost/sqlexdb
8 rows affected.


[('Bismarck',),
 ('Iowa',),
 ('Kongo',),
 ('North Carolina',),
 ('Renown',),
 ('Revenge',),
 ('Tennessee',),
 ('Yamato',)]

In [112]:
%%sql
SELECT name FROM Ships WHERE name = class
UNION
(
  SELECT DISTINCT ship FROM Outcomes
  INTERSECT
  SELECT class FROM Classes
)

-- cost       0.021577564999461
-- operations 6

 * postgresql://test:***@localhost/sqlexdb
8 rows affected.


[('Tennessee',),
 ('Revenge',),
 ('Yamato',),
 ('Kongo',),
 ('Renown',),
 ('North Carolina',),
 ('Iowa',),
 ('Bismarck',)]

In [115]:
%%sql
SELECT class FROM Classes
WHERE class IN (SELECT name FROM Ships) OR
      class IN (SELECT DISTINCT ship FROM Outcomes)
    
-- cost       0.011801740154624
-- operations 5

 * postgresql://test:***@localhost/sqlexdb
8 rows affected.


[('Bismarck',),
 ('Iowa',),
 ('Kongo',),
 ('North Carolina',),
 ('Renown',),
 ('Revenge',),
 ('Tennessee',),
 ('Yamato',)]

### #37
Find classes for which only one ship exists in the database (including the Outcomes table).

In [118]:
%%sql
SELECT c.class FROM Classes AS c
INNER JOIN (
  SELECT s.name, s.class FROM Ships AS s
  UNION
  SELECT o.ship AS name, o.ship AS class FROM Outcomes AS o
  WHERE ship NOT IN (SELECT name FROM Ships)
) all_s
ON all_s.class = c.class
GROUP BY c.class
HAVING COUNT(all_s.name) = 1

-- cost       0.037207894027233
-- operations 11

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('Bismarck',)]

In [119]:
%%sql
SELECT alls.class FROM (
  SELECT name, class FROM Ships 
  UNION
  SELECT o.ship, c.class FROM Classes AS c 
  LEFT JOIN Outcomes AS o ON c.class = o.ship
) alls 
GROUP BY alls.class
HAVING COUNT(alls.name) = 1

-- cost       0.027945596724749
-- operations 9

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('Bismarck',)]

### #38
Find countries that ever had classes of both battleships (‘bb’) and cruisers (‘bc’).

In [120]:
%%sql
SELECT c.country FROM (
  SELECT country, type FROM Classes
  GROUP BY country, type
) c
GROUP BY c.country
HAVING COUNT(*) = 2

-- cost       0.014959990978241
-- operations 5

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('Gt.Britain',), ('Japan',)]

In [122]:
%%sql
-- equivalent to the query above

SELECT country FROM Classes
GROUP BY country
HAVING COUNT(DISTINCT type) = 2

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('Gt.Britain',), ('Japan',)]

In [121]:
%%sql
SELECT country FROM classes WHERE type = 'bb'
INTERSECT
SELECT country FROM classes WHERE type = 'bc'

-- cost       0.019468391314149
-- operations 4

 * postgresql://test:***@localhost/sqlexdb
2 rows affected.


[('Gt.Britain',), ('Japan',)]

### #39
Find the ships that survived for future battles; that is, after being damaged in a battle, they participated in another one, which occurred later.

In [18]:
%%sql
WITH damaged_ships AS (
  SELECT o.ship, b.date, b.name, o.result
  FROM Outcomes AS o
  INNER JOIN Battles AS b ON b.name = o.battle
)

SELECT DISTINCT ds.ship FROM damaged_ships AS ds
WHERE ds.result = 'damaged' AND
  EXISTS (
    SELECT ds2.ship FROM damaged_ships AS ds2 
    WHERE ds2.ship = ds.ship AND ds2.date >= ds.date AND ds2.name != ds.name
  )

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('California',)]

### #40
Get the makers who produce only one product type and more than one model. Output: maker, type.

In [42]:
%%sql
WITH p AS (
  SELECT maker, type, COUNT(DISTINCT model) AS models_count
  FROM Product
  GROUP BY maker, type
)

SELECT p.maker, p.type FROM p
WHERE p.models_count > 1 AND
      p.maker IN (SELECT maker FROM p GROUP BY maker HAVING COUNT(maker) = 1)
    
-- cost       0.036692716181278
-- operations 11

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('D', 'Printer')]

In [43]:
%%sql
SELECT maker, MAX(type) as type FROM Product
GROUP BY maker 
HAVING COUNT(*) > 1 AND MAX(type) = MIN(type)

-- cost       0.015520420856774
-- operations 5

 * postgresql://test:***@localhost/sqlexdb
1 rows affected.


[('D', 'Printer')]

### #41
For each maker who has models at least in one of the tables PC, Laptop, or Printer, determine the maximum price for his products.
Output: maker; if there are NULL values among the prices for the products of a given maker, display NULL for this maker, otherwise, the maximum price.

In [50]:
%%sql
WITH all_products AS (
  SELECT p.maker, t.model, t.price 
  FROM Product AS p
  INNER JOIN (
    SELECT model, price FROM PC
    UNION
    SELECT model, price FROM Laptop
    UNION
    SELECT model, price FROM Printer
  ) t ON t.model = p.model
)

(
  SELECT a.maker, MAX(price) AS m_price 
  FROM all_products AS a
  WHERE NOT EXISTS (SELECT model FROM all_products WHERE price is NULL AND maker = a.maker)
  GROUP BY a.maker
)
UNION (
  SELECT a.maker, NULL AS m_price 
  FROM all_products AS a
  WHERE EXISTS (SELECT model FROM all_products WHERE price is NULL AND maker = a.maker)
  GROUP BY a.maker
)

-- cost       0.18495689332485
-- operations 39


 * postgresql://test:***@localhost/sqlexdb
5 rows affected.


[('A', Decimal('1150.00')),
 ('C', Decimal('970.00')),
 ('B', Decimal('1200.00')),
 ('E', Decimal('350.00')),
 ('D', Decimal('400.00'))]

In [49]:
%%sql
SELECT p.maker, IIF(COUNT(price) != COUNT(*), NULL, MAX(price)) AS m_price
FROM (
  select model, price FROM PC
  UNION ALL
  select model, price FROM Laptop
  UNION ALL
  select model, price FROM Printer
) a
INNER JOIN Product p ON p.model = a.model
GROUP BY p.maker

-- cost       0.038436122238636
-- operations 10
-- if use UNION without ALL than
-- cost       0.050530709326267
-- operations 11

 * postgresql://test:***@localhost/sqlexdb
6 rows affected.


[('1276', Decimal('400.00')),
 ('1433', Decimal('270.00')),
 ('1434', Decimal('290.00')),
 ('1401', Decimal('150.00')),
 ('1408', Decimal('270.00')),
 ('1288', Decimal('400.00'))]

### #42
Find the names of ships sunk at battles, along with the names of the corresponding battles.

In [51]:
%%sql
SELECT ship, battle
FROM Outcomes
WHERE result = 'sunk'

 * postgresql://test:***@localhost/sqlexdb
6 rows affected.


[('Bismarck', 'North Atlantic'),
 ('Fuso', 'Surigao Strait'),
 ('Hood', 'North Atlantic'),
 ('Kirishima', 'Guadalcanal'),
 ('Schamhorst', 'North Cape'),
 ('Yamashiro', 'Surigao Strait')]

### #43
Get the battles that occurred in years when no ships were launched into water.

In [ ]:
%%sql
